2018-11-28 11:46:39,894 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:46:40,116 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:46:44,990 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:46:45,652 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:46:46,020 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:46:46,461 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:46:50,129 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:00,223 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:01,101 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:01,675 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:02,293 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:03,118 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:03,596 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:04,033 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:04,423 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:04,713 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:05,254 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:05,546 ERROR: Exception on / [GET] [in d:\python\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "d:\python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PyCharm3\Links\app\routes.py", line 11, in index
  File "d:\python\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "d:\python\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "d:\python\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "d:\python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PyCharm3\Links\app\templates\index.html", line 1, in top-level template code
    <html>
  File "D:\PyCharm3\Links\app\templates\base.html", line 14, in top-level template code
  File "d:\python\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\python\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "d:\python\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "d:\python\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "d:\python\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'index' instead?
2018-11-28 11:47:11,261 INFO: Links startup [in D:\PyCharm3\Links\app\__init__.py:33]
2018-11-28 11:47:39,624 INFO: Links startup [in D:\PyCharm3\Links\app\__init__.py:33]
2018-11-28 11:48:55,320 INFO: Links startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 11:48:55,961 INFO: Links startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:02:11,627 INFO: Links startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:02:12,285 INFO: Links startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:03:54,674 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:03:55,377 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:04:22,432 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:04:47,235 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:04:47,933 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:30]
2018-11-28 13:10:30,290 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:10:30,992 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:12:08,510 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:12:09,228 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:12:36,883 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:12:43,994 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:12:52,657 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:12:53,412 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:16:27,950 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:20:03,793 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:20:46,197 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:22:55,654 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:23:50,017 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:26:47,772 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:26:48,491 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:29:26,959 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:29:27,633 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:30:43,236 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:30:43,704 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:30:43,922 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:30:56,655 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:30:56,905 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:32:20,859 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:32:21,562 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:33:01,811 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:33:02,538 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:34:59,783 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:35:00,517 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:39:25,861 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:39:26,549 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 13:56:42,886 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:35]
2018-11-28 14:03:39,374 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:03:40,171 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:13:26,274 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:13:27,081 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:17:06,090 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:17:06,878 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:22:44,970 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:22:45,791 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:23:20,746 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:23:21,466 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:23:50,978 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:23:51,730 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:32:50,115 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:32:50,937 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:35:28,767 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:35:29,516 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:36:26,011 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:36:26,793 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:40:06,840 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:40:24,126 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:40:24,838 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:40:57,939 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:40:58,682 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:41:10,558 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:41:32,289 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:41:41,617 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:41:42,347 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:42:49,447 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:42:50,196 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:47:52,647 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:47:53,399 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 14:50:07,980 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 17:46:29,740 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-28 17:46:30,504 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:02:32,415 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:02:33,196 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:03:25,506 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:03:33,224 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:03:33,958 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:05:51,340 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:05:52,134 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:09:08,722 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:09:09,587 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:16:14,945 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:16:15,770 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:22:52,819 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:23:04,809 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:24:16,075 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:27:37,088 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:27:37,856 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:34:39,271 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:34:40,021 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:35:21,334 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:35:22,073 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:35:58,654 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:35:59,442 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:39:15,983 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:39:16,777 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:41:02,768 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:41:03,504 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:42:04,340 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:42:05,117 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:46:38,328 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:47:57,755 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:49:46,583 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:51:00,551 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:51:18,796 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 09:51:19,573 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:00:37,531 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:00:38,235 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:07:59,510 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:09:20,147 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:12:51,258 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:12:52,007 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:16:24,341 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:16:50,290 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:18:53,256 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:18:53,979 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:19:21,884 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:19:22,587 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:19:47,995 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:19:48,714 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:27:30,160 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:27:30,878 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:29:07,938 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:29:08,637 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:29:17,142 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:29:46,551 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:42:45,674 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:42:46,492 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:43:25,737 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:43:45,249 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:44:33,424 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 10:58:42,668 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:04:35,138 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:04:35,912 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:05:03,110 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:06:19,700 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:07:34,035 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:10:44,614 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:11:38,073 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:12:13,982 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:12:14,735 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:14:54,735 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:14:55,457 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:17:07,743 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:18:46,026 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:18:46,859 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:18:53,362 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:19:51,406 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:20:04,456 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:26:04,172 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:26:04,967 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:26:07,472 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:26:08,218 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:26:54,284 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:26:55,033 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:30:41,672 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:31:30,465 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:33:05,509 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:39:10,348 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:49:29,559 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:49:30,294 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:50:08,346 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:50:14,799 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:51:01,635 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:51:11,818 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:51:12,570 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:51:46,241 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:51:49,694 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:51:54,552 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:51:55,318 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:56:13,459 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 11:56:14,218 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 12:57:14,325 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 12:57:15,060 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 12:57:23,344 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 12:57:24,033 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:21:38,215 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:21:39,003 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:35:56,546 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:35:57,367 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:46:43,197 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:46:43,970 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:46:52,091 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:46:52,827 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:47:00,796 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:47:01,572 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:47:18,103 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:47:18,867 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:48:35,487 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 13:48:36,264 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:16:14,708 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:16:15,494 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:21:36,583 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:25:39,800 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:25:40,581 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:26:37,184 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:29:41,296 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:30:31,752 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:30:49,214 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:31:08,752 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:31:19,594 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:34:15,196 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:36:28,355 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:37:42,618 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:40:18,492 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:40:19,209 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:41:23,547 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:41:58,302 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:42:48,275 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:44:57,438 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:44:58,155 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:50:06,218 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:51:57,298 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:52:23,459 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:55:33,983 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:55:34,500 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:55:34,703 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:55:45,339 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:55:46,026 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:57:10,277 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 14:57:11,045 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 15:15:13,373 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 16:36:42,297 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 16:36:43,044 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 17:12:49,461 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 17:12:50,211 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 17:44:32,854 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 17:44:33,567 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 18:22:31,282 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-29 18:22:32,075 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 09:02:45,022 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 09:02:45,761 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 09:12:28,126 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 09:53:14,473 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 09:53:15,208 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 11:39:04,603 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 11:39:06,012 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 14:14:46,940 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 14:14:47,673 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 16:03:30,687 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-11-30 16:03:31,523 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-12-04 09:10:31,237 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-12-04 09:10:32,009 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-12-04 11:04:55,029 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-12-04 11:04:55,811 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-12-04 11:09:07,412 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-12-04 11:09:08,192 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:38]
2018-12-04 15:36:19,455 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 15:36:20,242 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 16:05:57,934 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 16:05:58,730 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 16:21:49,198 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 16:21:49,963 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 16:44:56,409 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 16:45:45,141 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 16:46:11,979 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 16:55:33,428 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 16:55:34,161 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 16:56:12,605 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 16:57:45,369 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 16:58:03,169 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 16:58:17,734 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 17:04:51,062 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 17:04:53,281 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-04 17:04:53,968 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 09:02:35,474 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 09:02:36,239 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 09:04:39,707 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 09:05:09,787 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 09:15:45,840 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 09:20:16,176 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 09:20:59,516 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 09:22:54,617 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 09:24:50,676 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 09:49:34,269 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 09:50:08,075 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 09:50:45,677 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 09:58:40,454 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 09:59:23,307 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 09:59:50,393 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 11:01:59,464 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 11:02:22,006 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 11:03:31,185 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 11:04:49,489 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 11:06:30,396 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 11:06:40,435 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 11:06:52,853 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 11:09:47,586 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 11:10:05,740 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 11:10:34,844 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 11:12:12,512 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 11:33:54,457 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 11:36:11,759 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 11:36:12,536 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:06:42,265 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:09:35,781 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:09:39,025 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:11:28,431 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:21:52,846 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:25:57,591 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:25:58,373 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:26:16,426 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:26:51,541 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:27:07,239 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:28:58,737 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:29:26,021 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:31:05,807 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:31:32,259 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:35:48,305 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:37:12,982 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:42:55,985 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:46:04,972 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:46:12,698 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:46:34,177 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:46:59,312 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:48:01,842 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:48:18,977 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:48:35,717 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:49:15,536 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:51:18,424 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 13:51:41,014 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:17:00,679 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:17:01,455 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:23:30,545 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:23:48,642 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:26:38,523 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:27:27,757 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:34:17,785 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:38:57,379 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:39:21,148 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:39:59,821 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:40:32,664 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:41:13,669 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:52:24,922 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:53:23,925 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:54:15,587 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 15:54:54,271 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:04:34,485 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:05:23,692 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:06:48,703 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:17:47,483 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:40:30,545 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:40:31,326 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:41:41,334 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:45:12,129 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:45:33,503 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:46:14,865 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:46:48,570 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:47:23,250 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:49:28,136 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:53:50,941 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:55:02,955 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:55:35,511 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:55:58,880 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:56:13,150 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 16:56:39,952 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 17:01:04,992 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 17:01:13,800 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 17:30:45,573 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 17:30:46,360 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 17:32:17,368 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 17:34:24,612 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 17:34:42,347 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 17:37:01,054 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 17:38:04,282 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 17:39:57,831 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-05 17:40:06,565 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 10:55:34,272 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 10:57:01,449 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 10:57:09,162 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:03:09,052 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:03:20,277 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:03:26,807 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:15:07,654 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:16:02,616 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:28:27,017 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:36:01,240 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:36:01,958 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:37:15,731 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:39:39,267 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:39:45,702 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:39:54,724 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:40:02,392 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:42:10,321 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:43:31,722 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 11:43:42,662 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 13:16:55,697 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 13:29:43,240 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 13:35:43,718 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 13:37:25,017 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 13:51:14,393 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 13:52:13,582 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 13:53:18,385 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 13:53:39,405 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 13:53:57,027 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 13:57:14,324 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 13:58:52,102 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 13:59:09,964 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 14:00:59,797 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 14:02:49,574 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 14:04:18,051 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 14:50:24,323 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 15:32:33,651 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-06 16:16:05,226 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:39]
2018-12-07 09:30:55,373 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:40]
2018-12-07 10:00:39,054 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:40]
2018-12-07 10:12:48,003 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:40]
2018-12-07 10:13:41,989 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:40]
2018-12-07 10:22:25,830 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:41]
2018-12-07 10:35:04,887 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:41]
2018-12-07 10:35:18,144 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:41]
2018-12-07 10:35:35,662 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:41]
2018-12-07 10:38:34,714 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:41]
2018-12-07 10:56:42,768 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 10:58:21,256 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 10:59:13,178 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 11:34:45,404 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 11:34:46,264 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 11:35:21,746 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 11:41:52,553 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 13:42:03,229 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 13:43:37,298 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 13:44:34,494 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 13:47:12,634 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 13:48:11,505 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 13:51:33,153 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 13:52:47,330 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 13:53:14,480 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 13:53:51,450 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 13:54:15,034 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 13:55:14,440 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 13:55:41,524 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 13:56:05,040 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 13:59:09,362 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 14:01:14,717 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 14:10:02,043 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 14:18:17,530 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 14:24:09,194 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-07 14:25:54,932 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-10 17:17:25,572 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-10 17:17:26,338 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-10 17:17:31,653 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-10 17:18:00,656 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-10 17:18:54,540 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-10 17:19:24,823 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-10 17:20:47,733 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-10 17:33:36,958 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 09:45:33,183 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 09:45:33,932 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 09:46:37,651 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 09:49:33,462 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 09:49:34,353 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 09:50:07,703 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 09:51:36,961 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 09:51:38,208 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 09:52:01,726 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 09:54:09,922 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 09:54:10,787 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 09:55:27,814 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 09:57:37,797 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 09:57:38,626 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:01:36,881 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:01:37,686 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:01:51,002 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:06:07,692 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:07:00,140 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:07:48,424 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:08:40,780 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:34:40,017 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:36:41,135 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:37:47,991 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:38:44,781 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:39:06,973 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:39:15,836 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:50:19,302 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:52:15,739 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 10:56:42,435 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:19:14,930 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:19:32,664 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:19:35,913 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:21:59,979 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:22:30,242 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:23:27,520 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:24:30,343 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:25:22,256 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:26:05,977 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:32:52,525 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:36:52,935 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:36:53,746 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:37:30,415 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:38:57,387 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:38:58,170 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:40:16,492 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:40:29,839 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 11:41:09,153 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:11:14,893 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:11:30,672 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:12:31,889 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:13:02,299 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:24:19,951 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:25:24,775 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:27:51,572 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:27:51,588 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:27:52,862 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:29:31,550 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:29:31,566 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:30:04,471 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:30:05,660 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:31:29,904 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:31:44,304 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:31:53,863 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:32:21,395 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:33:08,053 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:33:17,845 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:33:54,717 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:34:22,218 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:40:34,456 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:41:07,087 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:41:38,336 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:42:03,742 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:42:55,895 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:44:00,651 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 13:44:15,277 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:03:21,660 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:07:20,693 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:07:21,957 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:07:48,063 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:11:02,761 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:13:02,953 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:13:16,762 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:15:59,649 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:18:26,539 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:20:50,533 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:25:02,835 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:26:23,377 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:27:15,627 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:32:52,549 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:32:53,801 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:33:20,746 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:36:36,310 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:45:36,077 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:49:21,006 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:50:35,143 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:50:57,044 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:52:59,616 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:53:43,186 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:56:39,231 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 14:57:07,369 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:00:00,106 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:05:00,151 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:05:19,753 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:12:30,493 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:14:57,158 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:15:13,389 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:15:45,979 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:23:40,774 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:24:06,498 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:24:25,218 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:25:55,861 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:26:02,122 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:27:21,292 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:31:33,408 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:32:02,816 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:32:22,366 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:33:57,845 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:33:59,093 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:34:30,681 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:36:16,518 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:36:39,957 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:36:57,375 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:37:07,375 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:38:20,235 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:40:23,686 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:40:35,480 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:42:02,219 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:42:03,424 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:42:42,436 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:49:32,994 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:50:22,824 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:50:38,759 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:51:01,033 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:51:12,431 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:51:40,533 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:52:40,233 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:54:05,512 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:56:15,238 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 15:57:50,407 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:04:08,144 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:04:30,696 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:05:10,907 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:05:39,686 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:07:04,842 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:07:47,484 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:09:13,778 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:10:18,890 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:21:03,611 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:21:04,703 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:21:39,250 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:22:21,720 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:22:38,485 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:22:56,426 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:23:09,461 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:31:52,419 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:44:08,191 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:44:09,328 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:44:31,982 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:44:35,679 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:44:58,198 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:45:16,370 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:49:50,526 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:50:17,008 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:55:57,896 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-11 16:57:44,914 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-12 13:49:26,409 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-12 13:50:25,064 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-12 14:05:32,981 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-12 14:10:49,653 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-12 14:21:52,130 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-12 14:50:48,197 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-14 09:30:35,148 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-14 09:34:37,866 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-14 09:46:40,939 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-14 10:15:34,481 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-14 10:24:21,818 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-14 10:24:22,879 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-14 12:47:12,196 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-14 13:16:35,077 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-14 13:16:36,384 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-17 10:43:42,793 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-17 10:43:44,003 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-17 10:44:35,144 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-17 10:57:18,122 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-17 10:57:19,294 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-17 10:57:55,049 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-17 11:06:11,345 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
2018-12-17 11:07:03,644 INFO: Links Startup [in D:\PyCharm3\Links\app\__init__.py:53]
